name: Github Actions Crawl

on:
    workflow_dispatch:

jobs:
    spider:
        runs-on: ubuntu_latest
        defaults:
            run:
                working-directory: ./cinema_scraper_project/
        
        strategy:
            matrix:
                python-version: [3.10]
        
        env:
            scrapeops_api_key: ${{ secrets.SCRAPEOPS_API_KEY }}

        steps:
            - uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: ${{ matrix.python-version }}
            
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r ../requirements.txt

            - name: Run spider
              run: scrapy crawl cinestar_program_spider
