name: Test env ls

on:
    workflow_dispatch:

jobs:
    spider:
        runs-on: ubuntu-latest
        
        strategy:
            matrix:
                python-version: ['3.10']
        
        env:
            SCRAPEOPS_API_KEY: ${{ secrets.SCRAPEOPS_API_KEY }}
            MONGODB_URI: ${{ secrets.MONGODB_URI }}
            MONGODB_DATABASE: ${{ secrets.MONGODB_DATABASE }}

        steps:
            - uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: ${{ matrix.python-version }}
            
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

            - name: ls test
              run: |
                cd /opt/hostedtoolcache/Python/3.10.12/x64/lib
                ls
            
            - name: ls test2
              run: |
                pip show scrapy-selenium

            - name: ls test3
              run: |
                cd /opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages
                ls

            - name: ls test4
              run: |
                cd /opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/scrapy-selenium
                ls
